feat(226): implement GraalVM native image support

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -1,7 +1,10 @@
-name: Build and Push Docker Image
+name: Build and Push Native Docker Image
 
 on:
   push:
+    branches:
+      - main
+  pull_request:
     branches:
       - main
 
@@ -16,11 +19,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - name: Set up GraalVM 22 with Native Image
+        uses: graalvm/setup-graalvm@v1
         with:
           java-version: '17'
-          distribution: 'temurin'
+          distribution: 'graalvm'
+          components: 'native-image'
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Cache Maven packages
         uses: actions/cache@v3
@@ -42,13 +47,13 @@ jobs:
                   </servers>
                 </settings>" > ~/.m2/settings.xml
 
-      - name: Build JAR
-        run: mvn clean package -DskipTests
+      - name: Build Native Executable
+        run: mvn -Pnative native:compile -DskipTests
 
-      - name: Verify JAR File Exists
+      - name: Verify Native Binary Exists
         run: |
-          if [ ! -f ./online-banking-app/target/online-banking-app-0.1-SNAPSHOT.jar ]; then
-            echo "JAR file not found!" && exit 1
+          if [ ! -f ./online-banking-app/target/online-banking-app ]; then
+            echo "Native binary not found!" && exit 1
           fi
 
       - name: Log in to GHCR
@@ -58,10 +63,12 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GHCR_PAT }}
 
-      - name: Build Docker image
+      - name: Build Docker Image with Native Binary
         run: |
-          docker build -t ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }} .
+          docker build \
+            --build-arg BUILD_TYPE=native \
+            -t ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }} .
 
-      - name: Push Docker image to GHCR
+      - name: Push Docker Image to GHCR
         run: |
           docker push ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }}
