chore(): Updated the docker-build.yaml file to have thesha of the commit as tag

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -1,15 +1,17 @@
 name: Build and Push Docker Image
+
 on:
-  pull_request:
+  push:
     branches:
-      - main
+      - Create-workflow-for-build-image-to-GHCR
+
 jobs:
   build:
-    if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     permissions:
       packages: write
       contents: read
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -19,8 +21,9 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+
       - name: Cache Maven packages
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
@@ -43,7 +46,10 @@ jobs:
         run: mvn -f online-banking-app/pom.xml clean package -DskipTests
 
       - name: Verify JAR File Exists
-        run: ls -l ./online-banking-app/target/online-banking-app-0.1-SNAPSHOT.jar
+        run: |
+          if [ ! -f ./online-banking-app/target/online-banking-app-0.1-SNAPSHOT.jar ]; then
+            echo "JAR file not found!" && exit 1
+          fi
 
       - name: Log in to GHCR
         uses: docker/login-action@v3
@@ -54,8 +60,8 @@ jobs:
 
       - name: Build Docker image
         run: |
-          docker build -t ghcr.io/adorsys-gis/webank-online-banking:latest .
+          docker build -t ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }} .
 
       - name: Push Docker image to GHCR
         run: |
-          docker push ghcr.io/adorsys-gis/webank-online-banking:latest
+          docker push ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }}
